# Generated by Django 4.2.19 on 2025-02-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_images',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to=''),
        ),
    ]
