# Generated by Django 4.2.19 on 2025-02-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_created_at_tag_created_remove_tag_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_images',
            field=models.ImageField(blank=True, default='images/default.jpg', max_length=2000, null=True, upload_to=''),
        ),
    ]
